### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by deveras** [stevemao/grunt-remove-html-comments#1]
There are some good opportunities for production comments. For example, IE does not support PNG favicons until version 11. A conditional comment for favicons in IE 9 and below:
`<!--[if IE]><link rel="shortcut icon" href="path/to/favicon.ico"><![endif]-->`

Hope you can look in to it

**Comment by stevemao** [comment]
Well the original thought of the project was to remove all comments (including conditional comments). It's meant to be simple and fast... You might wanna checkout https://github.com/gruntjs/grunt-contrib-htmlmin?

**Comment by stevemao** [comment]
@deveras I have made https://github.com/stevemao/html-non-conditional-comment-regex but i'm not very keen to use it because only oldie is using it. However PR welcome if you really need it.
